# Generated by Django 2.2 on 2022-06-25 15:13

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataroti',
            fields=[
                ('kode', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='datasales',
            fields=[
                ('nik', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=13)),
                ('Email', models.CharField(max_length=50)),
                ('jenis_kelamin', models.CharField(choices=[('laki-laki', 'laki-laki'), ('perempuan', 'perempuan')], default='laki-laki', max_length=10)),
                ('pilih_status', models.CharField(choices=[('menikah', 'menikah'), ('belum menikah', 'belum menikah')], default='menikah', max_length=13)),
                ('pilih_sales_type', models.CharField(choices=[('ML', 'MOBIL'), ('MR', 'MOTOR')], default='ML', max_length=10)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_berakhir', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='datatoko',
            fields=[
                ('kode', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('pemilik', models.CharField(max_length=50)),
                ('no_hp', models.CharField(max_length=13)),
                ('Email', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
                ('Jenis_toko', models.CharField(choices=[('P&D', 'P&D'), ('WARUNG RE/NOO', 'WARUNG RE/NOO'), ('MTI RE/NOO', 'MTI RE/NOO')], default='P&D', max_length=13)),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_akun_name', models.CharField(max_length=50)),
                ('npwp_no', models.CharField(max_length=15)),
                ('name_npwp', models.CharField(max_length=50)),
                ('provinsi', models.CharField(max_length=50)),
                ('kabupaten_kota', models.CharField(max_length=50)),
                ('kecamatan', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('longtitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='jadwal_kunjungan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=100)),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sari_roti.datasales')),
                ('toko_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sari_roti.datatoko')),
            ],
        ),
        migrations.CreateModel(
            name='datadistribusi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('roti_sisa', models.IntegerField(blank=True, null=True)),
                ('dropping', models.IntegerField()),
                ('roti_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sari_roti.dataroti')),
                ('toko_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sari_roti.datatoko')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_sales', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
