# Generated by Django 2.2 on 2022-06-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sari_roti', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
