# Generated by Django 2.2 on 2022-06-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sari_roti', '0002_delete_useraccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasales',
            old_name='pilih_sales_type',
            new_name='sales_type',
        ),
        migrations.RenameField(
            model_name='datasales',
            old_name='pilih_status',
            new_name='status',
        ),
    ]
