# Generated by Django 2.2 on 2022-06-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sari_roti', '0003_auto_20220626_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasales',
            name='nik',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
