# Generated by Django 2.2 on 2022-06-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sari_roti', '0004_auto_20220626_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasales',
            name='nik',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
