# Generated by Django 2.2 on 2022-06-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sari_roti', '0005_auto_20220626_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadistribusi',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='datasales',
            name='tanggal_berakhir',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='datasales',
            name='tanggal_mulai',
            field=models.DateField(auto_now_add=True),
        ),
    ]
