# Generated by Django 2.2 on 2022-06-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sari_roti', '0006_auto_20220626_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatoko',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
    ]
