# Generated by Django 2.2 on 2022-06-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sari_roti', '0007_auto_20220626_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadistribusi',
            name='tanggal',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='datasales',
            name='tanggal_berakhir',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='datasales',
            name='tanggal_mulai',
            field=models.DateField(),
        ),
    ]
