# Generated by Django 2.2 on 2022-08-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sari_roti', '0008_auto_20220626_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal_kunjungan',
            name='hari',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10),
        ),
    ]
