# Generated by Django 2.2 on 2022-08-25 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sari_roti', '0012_jumlahdistribusiperhari'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jumlahdistribusiperhari',
        ),
    ]
