# Generated by Django 2.2 on 2022-08-25 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sari_roti', '0013_delete_jumlahdistribusiperhari'),
    ]

    operations = [
        migrations.CreateModel(
            name='jumlahdistribusiperhari',
            fields=[
                ('tanggal', models.DateField(primary_key=True, serialize=False)),
                ('jumlah_drop', models.CharField(max_length=100)),
                ('jumlah_sisa', models.CharField(max_length=100)),
                ('toko_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sari_roti.datatoko')),
            ],
        ),
    ]
