# Generated by Django 2.2 on 2022-08-31 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sari_roti', '0018_datadistribusi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='datadistribusi',
        ),
    ]
