# Generated by Django 2.2 on 2022-08-31 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sari_roti', '0019_delete_datadistribusi'),
    ]

    operations = [
        migrations.CreateModel(
            name='datadistribusi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('dropping', models.IntegerField()),
                ('roti_sisa', models.IntegerField(blank=True, null=True)),
                ('roti_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sari_roti.dataroti')),
                ('toko_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sari_roti.datatoko')),
            ],
        ),
    ]
